name: Docker Build Cloud

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container  # Utilisation du pilote docker-container
          install: true
          builder: default

      # Étape 5 : Construire les images avec Docker Compose
      - name: Build Docker Compose services
        run: docker compose -f docker-compose.override.yml build

      # Étape 6 : Pousser les images construites vers Docker Hub
      - name: Push Docker Compose services
        run: docker compose -f docker-compose.override.yml push

